### ISSUE TITLE
Gitleaks returns exit code 0 when a sequence of invalid flags is passed

### ISSUE THREAD

**Issue by tiagotaveira-feedzai** [gitleaks/gitleaks#1464]
**Describe the bug**
Gitleaks returns exit code 0 when the order of the flags should have caused it to fail (and return exit code 1).

**To Reproduce**
1. `touch config.toml`
2. `gitleaks detect -s --no-banner . -c config.toml`
3. `echo $?` (0 is returned, despite the output showing the error)

**Expected behavior**
Return exit code 1 (leaks or error encountered).

**Screenshots**
n/a

**Basic Info (please complete the following information):**
 - OS: macOS 14.5 (23F79)
 - Gitleaks Version: 8.18.4

**Additional context**
Not passing the config file flag (i.e., `gitleaks detect -s --no-banner .`) returns the expected exit code (1).
I ran into this by chance due to having misplaced the arguments, other flag combinations possibly have the same behavior.

cc @zricethezav

**Comment by rgmz** [comment]
I think this should be fixed by #1461.

```sh
$ ./gitleaks detect -s --no-banner . -c config.toml

    ○
    │╲
    │ ○
    ○ ░
    ░    gitleaks

11:14PM ERR [git] fatal: cannot change to '--no-banner': No such file or directory
11:14PM ERR failed to scan Git repository error="stderr is not empty"
11:14PM WRN partial scan completed in 3.72ms
11:14PM WRN no leaks found in partial scan

$ echo $?
1
```

**Comment by recreator66** [comment]
This still exists @rgmz 

```
./gitleaks detect -s --no-banner . -c config.toml

    ○
    │╲
    │ ○
    ○ ░
    ░    gitleaks

8:34PM ERR [git] fatal: cannot change to '--no-banner': No such file or directory
8:34PM ERR failed to scan Git repository error="stderr is not empty"
8:34PM INF scan completed in 1.07ms
8:34PM INF no leaks found

echo $?                                                                                                                                                       
0
```

I think this is because the error is only logged instead of terminating with exit code 1:
https://github.com/gitleaks/gitleaks/blob/c5b15c9d74036ca0c32134280c3d941b41e4f2d9/cmd/detect.go#L117-L120

With the replacement of  `log.Error().Err(err).Msg("failed to scan Git repository")` by `log.Fatal().Err(err).Msg("failed to scan Git repository")` we could fix this issue. 

```
./gitleaks detect -s --no-banner . -c config.toml

    ○
    │╲
    │ ○
    ○ ░
    ░    gitleaks

8:36PM ERR [git] fatal: cannot change to '--no-banner': No such file or directory
8:36PM FTL failed to scan Git repository error="stderr is not empty"

echo $?                                                                                                                                                   
1
```
What is the purpose to only log this error?

**Comment by rgmz** [comment]
Hmm, must be a regression from #1504.

**Comment by recreator66** [comment]
Just have seen the deprecation comments, wasn't aware of this change tbh.

However executing the same flags with `directory` does not throw an error at all..   
How should we proceed here? Does it make sense to update the logic for the old command `detect` and should `directory` terminate the execution in case there a an empty config passed?
```
./gitleaks directory --no-banner -c config.toml 
9:29PM INF scan completed in 7.83ms
9:29PM INF no leaks found

echo $?
0
```

**Comment by matthernet** [comment]
Any update on this fix?

**Comment by boly38** [comment]
I've the same need : a typo in arg or a 0 commit scanned must return 1 as status, 
else we have green light without real analysis, so a risky false negative

Just another example
```
$ docker run --rm -v "${PWD}:/src" -w /src docker.io/zricethezav/gitleaks:latest detect --exit-code 1 --log-opts=\"--since='2022-01-01'\" --source=/src --report-path=/src/reports/gitleaks.native.json --no-banner --verbose
9:44AM WRN the following `--log-opts` values may not work as expected: ["--since=2022-01-01"]
        see https://github.com/gitleaks/gitleaks/issues/1153 for more information
9:44AM ERR [git] fatal: ambiguous argument '"--since=2022-01-01"': unknown revision or path not in the working tree.
9:44AM ERR [git] Use '--' to separate paths from revisions, like this:
9:44AM ERR [git] 'git <command> [<revision>...] -- [<file>...]'
9:44AM INF Unknown SCM platform. Use --platform to include links in findings. host=gitlab.tech.orange
9:44AM ERR error="stderr is not empty"
9:44AM INF 0 commits scanned.
9:44AM INF scanned ~0 bytes (0) in 43.9ms
9:44AM INF no leaks found
$ echo $?
0
```

**Comment by CAOShurong** [comment]
## Reproduced on current `master` — the bug is still open (the git-scan path, not the source path)

I built gitleaks from `master` (`718896a`) and reproduced this on a fresh git repo.

**Setup:** repo with one real leaked key committed (`aws_key = AKIAIOSFODNN7EXAMPLE`), then run a scan whose git range is invalid:

```text
$ gitleaks detect --log-opts "nonexistentref..HEAD"
5:58PM ERR [git] Use '--' to separate paths from revisions, like this:
5:58PM ERR [git] 'git <command> [<revision>...] -- [<file>...]'
5:58PM ERR error="stderr is not empty"
5:58PM INF 0 commits scanned.
5:58PM INF scanned ~0 bytes (0) in 83.2ms
5:58PM INF no leaks found
$ echo $?
0
```

The scan **completely failed** (0 commits scanned, the git error is logged as `ERR`), yet the process exits `0` and prints `no leaks found`. In a CI gate this is a silent false-pass: a broken `--log-opts` / corrupted git history / git version mismatch can make gitleaks report "clean" while scanning nothing.

**Controls that confirm the regression is specific to the git-scan path:**
- Source-resolution failure *is* correctly fatal now: `gitleaks detect -s /nonexistent-path` → `FTL … The system cannot find the file specified.` and exits `1`. So the 2024 fix family works for the filesystem source but not for the git history source.
- A valid range over the same secret → `1 commits scanned` and the finding is produced (exit `1`), proving the secret/rule side is fine; only the *failed-scan* branch is wrong.

### Root cause (exact locations)

In `cmd/detect.go`, the git-history branch:

```go
findings, err = detector.DetectSource(cmd.Context(), &sources.Git{ … })

if err != nil {
    // don't exit on error, just log it
    logging.Error().Err(err).Msg("failed to scan Git repository")   // ← swallows err
}
```

The error is logged but **not propagated**. `findingSummaryAndExit` (in `cmd/root.go`) only ever calls `os.Exit(1)` via `if err != nil { os.Exit(1) }` (root.go:493) — but by the time it is called, `err` has been reset to `nil` by the swallow, so the exit decision falls through to `if len(findings) != 0` → `0` findings → exit `0`. The filesystem source path went through `logging.Fatal` and exits correctly; the git path was left with the old "log and continue" block, which is the live bug. (`cmd/git.go` and `cmd/protect.go` carry the identical swallow pattern.)

### Design note on the `log.Fatal` suggestion in this thread

Switching the swallow to `logging.Fatal().Err(err).Msg(...)` (as suggested above) *would* make a failed scan exit non-zero, but it is the wrong fix: `Fatal` aborts the entire run on **any** git hiccup, discarding every finding already collected from the working tree and other commits. gitleaks intentionally supports *partial* scans (the `partial scan completed` / `no leaks found in partial scan` warnings exist for exactly this). The clean fix is the smaller one: **stop swallowing the error** so the existing `if err != nil { os.Exit(1) }` in `findingSummaryAndExit` fires. A genuinely *partial* scan (some commits read, one ref unreadable) still keeps its current behavior; a *fully failed* scan becomes a deterministic non-zero exit instead of a false green. No new control flow, no lossy `Fatal`.

### Ask / offer

This is a real CI-safety bug (false "no leaks found" on a scan that read 0 commits), and the prior #1461 fix only closed the `DetectGit`/diff side. I can open a minimal PR that removes the swallow in `cmd/detect.go` (and mirror it in `cmd/git.go` / `cmd/protect.go`) with a regression test asserting that a failed git scan exits non-zero — happy to do so if a maintainer confirms the "propagate, don't Fatal" direction.

*(Prepared with AI assistance; reproduction and root-cause analysis above are from a source build of `master` and a local repro repo.)*
